---
default_language_version:
  python: python3.12

repos:
  #################################################################
  # Generic pre-commit hooks
  #################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      # - id: forbid-tabs
      # - id: remove-tabs
      #  args: [--whitespaces-count, '2']
      # - id: chmod
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [push]

  #################################################################
  # Other file linting
  #################################################################
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
        args: [-c, ./.utility/config/yamllint.yml]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-workflows

#  #################################################################
#  # Make / shell hooks
#  #################################################################
#  - repo: https://github.com/mrtazz/checkmake.git
#    # Or another commit hash or version
#    rev: 0.2.2
#    hooks:
#      # Use this hook to let pre-commit build checkmake in its sandbox
#      - id: checkmake
#      # OR Use this hook to use a pre-installed checkmark executable
#      # -   id: checkmake-system
#  - repo: https://github.com/shellcheck-py/shellcheck-py
#    rev: v0.9.0.5
#    hooks:
#      - id: shellcheck

  #################################################################
  # Credentials / secrets
  #################################################################
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
