---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
      - github-actions
  # workflow_dispatch:
  # schedule:
  #   - cron: "1 1 * * 3"

env:
  WORKING_DIR: 'mark-three.install_deb_packages'

defaults:
  run:
    working-directory: '$WORKING_DIR'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: '$WORKING_DIR'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        # run: pip3 install yamllint
        run: pip install -r requirements-dev.txt

      - name: Lint code.
        run: |
          yamllint -c ./.utility/config/yamllint.yml .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          # RHEL 8 / Rocky 8 will never work with latest Ansible 2.17+
          #   https://github.com/ansible/ansible/issues/82068#issuecomment-2135279350
          # - rockylinux8
          # - rockylinux9
          # - ubuntu2204
          # - ubuntu2004
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: '$WORKING_DIR'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker
        # run: pip3 install ansible==2.9 molecule molecule-plugins[docker] docker

      # # Molecule is proving quite difficult to work with and the documentation is sub optimal, I am pressing pause on
      # # testing this for now and commenting the test out. May or may not get back to these in the future
      # - name: Run Molecule tests.
      #   run: molecule test
      #   env:
      #     PY_COLORS: '1'
      #     ANSIBLE_FORCE_COLOR: '1'
      #     MOLECULE_DISTRO: ${{ matrix.distro }}
